// packages/web-component/src/jiwo-qr.ts
import {
  JiwoWebGLRenderer,
  RenderMode,
  RenderModel,
  isWebGLSupported,
  render2DFallbackCanvas,
} from '@jiwoqr/renderer-webgl';
import { encodeQR } from '@jiwoqr/core';

export class JiwoQRElement extends HTMLElement {
  private renderer?: JiwoWebGLRenderer;
  private fallbackCanvas?: HTMLCanvasElement;
  private isFallback = false;

  static get observedAttributes() {
    return ['value', 'model', 'mode'];
  }

  connectedCallback() {
    this.style.display = 'block';
    this.style.width = this.style.width || '100%';
    this.style.height = this.style.height || '100%';
    this.style.position = 'relative';

    const value = this.getAttribute('value') || 'https://jiwoqr.dev';
    const model = (this.getAttribute('model') as RenderModel) || 'architecture';
    const mode = (this.getAttribute('mode') as RenderMode) || '3d';

    if (isWebGLSupported()) {
      try {
        this.renderer = new JiwoWebGLRenderer({
          container: this,
          model,
          mode,
        });
        this.renderer.setData(value);
        this.isFallback = false;
        return;
      } catch (err) {
        console.warn('[JiwoQRElement] WebGL initialization failed. Falling back to 2D canvas.', err);
        this.isFallback = true;
      }
    } else {
      this.isFallback = true;
    }

    if (this.isFallback) {
      this.innerHTML = '';
      const canvas = document.createElement('canvas');
      canvas.width = this.clientWidth || 300;
      canvas.height = this.clientHeight || 300;
      canvas.style.width = '100%';
      canvas.style.height = '100%';
      canvas.style.display = 'block';
      canvas.style.objectFit = 'contain';
      this.appendChild(canvas);
      this.fallbackCanvas = canvas;
      this.renderFallback(value);
    }
  }

  private renderFallback(val: string) {
    if (!this.fallbackCanvas) return;
    try {
      const matrix = encodeQR(val);
      render2DFallbackCanvas(this.fallbackCanvas, matrix);
    } catch {
      // Ignore invalid input during typing
    }
  }

  disconnectedCallback() {
    this.renderer?.dispose();
    this.renderer = undefined;
    this.fallbackCanvas?.remove();
    this.fallbackCanvas = undefined;
  }

  attributeChangedCallback(name: string, oldValue: string, newValue: string) {
    if (oldValue === newValue) return;

    if (this.renderer) {
      if (name === 'value') {
        this.renderer.setData(newValue);
      } else if (name === 'mode') {
        this.renderer.setMode(newValue as RenderMode);
      } else if (name === 'model') {
        this.renderer.setModel(newValue as RenderModel);
      }
    } else if (this.isFallback && name === 'value') {
      this.renderFallback(newValue);
    }
  }

  public setMode(mode: RenderMode) {
    this.setAttribute('mode', mode);
    this.renderer?.setMode(mode);
  }

  public setModel(model: RenderModel) {
    this.setAttribute('model', model);
    this.renderer?.setModel(model);
  }

  public setMorphProgress(progress: number) {
    this.renderer?.setMorphProgress(progress);
  }
}

if (typeof customElements !== 'undefined' && !customElements.get('jiwo-qr')) {
  customElements.define('jiwo-qr', JiwoQRElement);
}

// packages/react/src/JiwoQR.tsx
import React, { useEffect, useRef } from 'react';
import {
  JiwoWebGLRenderer,
  RenderMode,
  RenderModel,
  isWebGLSupported,
  render2DFallbackCanvas,
} from '@jiwoqr/renderer-webgl';
import { encodeQR } from '@jiwoqr/core';

export interface JiwoQRProps {
  /** Target URL or data to encode */
  value: string;
  /** Visual 3D model archetype */
  model?: RenderModel;
  /** Display mode ('3d' interactive world or 'scan' flat 2D) */
  mode?: RenderMode;
  /** Width / height styling */
  className?: string;
  style?: React.CSSProperties;
  /** Transition morph duration in ms (default 800) */
  morphDuration?: number;
}

export const JiwoQR: React.FC<JiwoQRProps> = ({
  value,
  model = 'architecture',
  mode = '3d',
  className,
  style,
  morphDuration = 800,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<JiwoWebGLRenderer | null>(null);
  const fallbackCanvasRef = useRef<HTMLCanvasElement | null>(null);
  const isFallbackRef = useRef<boolean>(false);

  useEffect(() => {
    if (!containerRef.current) return;

    if (isWebGLSupported()) {
      try {
        const renderer = new JiwoWebGLRenderer({
          container: containerRef.current,
          model,
          mode,
          morphDuration,
        });
        rendererRef.current = renderer;
        renderer.setData(value);
        isFallbackRef.current = false;

        return () => {
          renderer.dispose();
          rendererRef.current = null;
        };
      } catch (err) {
        console.warn('[JiwoQR] WebGL initialization failed. Falling back to 2D canvas.', err);
        isFallbackRef.current = true;
      }
    } else {
      isFallbackRef.current = true;
    }

    // Zero-WebGL Fallback branch
    if (isFallbackRef.current && containerRef.current) {
      const canvas = document.createElement('canvas');
      canvas.width = containerRef.current.clientWidth || 300;
      canvas.height = containerRef.current.clientHeight || 300;
      canvas.style.width = '100%';
      canvas.style.height = '100%';
      canvas.style.display = 'block';
      canvas.style.objectFit = 'contain';

      containerRef.current.innerHTML = '';
      containerRef.current.appendChild(canvas);
      fallbackCanvasRef.current = canvas;

      try {
        const matrix = encodeQR(value);
        render2DFallbackCanvas(canvas, matrix);
      } catch {
        // Ignore encoding error if payload is empty/invalid
      }

      return () => {
        canvas.remove();
        fallbackCanvasRef.current = null;
      };
    }
  }, []);

  useEffect(() => {
    if (rendererRef.current) {
      rendererRef.current.setData(value);
    } else if (isFallbackRef.current && fallbackCanvasRef.current) {
      try {
        const matrix = encodeQR(value);
        render2DFallbackCanvas(fallbackCanvasRef.current, matrix);
      } catch {
        // Ignore encoding error
      }
    }
  }, [value]);

  useEffect(() => {
    if (rendererRef.current) {
      rendererRef.current.setMode(mode);
    }
  }, [mode]);

  useEffect(() => {
    if (rendererRef.current) {
      rendererRef.current.setModel(model);
    }
  }, [model]);

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        width: '100%',
        height: '100%',
        position: 'relative',
        overflow: 'hidden',
        ...style,
      }}
    />
  );
};
